### PR TITLE
ITKwarps and ants-based correction of unfolded space

### PR DESCRIPTION
**Pull request by akhanf**
OK this should be the last PR for gifti/warp integration:

I also moved these scripts into a tools/warps_gifti subfolder to keep things more organized

The warps created are now:
- Warp_unfold2native.nii   (for surfaces from unfold to native)
- Warp_native2unfold.nii   (for surfaces from native to unfold)
- Warp_unfold2native_extrapolateNearest.nii  (voxels outside are mapped to nearest)
- WarpITK_unfold2native.nii (for images from unfold to native, derived from Warp_native2unfold.nii)
- WarpITK_native2unfold.nii (for images from native to unfold,derived from Warp_unfold2native.nii)

The brand new ones are:
- WarpITK_unfold2unfoldtemplate_0Warp.nii.gz
- WarpITK_unfold2unfoldtemplate_0InverseWarp.nii.gz
- Warp_unfold2unfoldtemplate.nii (for warping surfaces)
- Warp_unfoldtemplate2unfold.nii (for fullgrid template surfaces to subject unfolded space)

These are from an ANTS registration between the unfolded coords-IO and a fullgrid coords-IO, to account for the fact that the unfolded space doesn't occupy the entire unfolded space. I tried a number of different schemes for this, and what worked best is a two-channel registration with smoothed binary volumes representing the inner and outer volume (e.g. 0<IO <0.5 and 0.5<IO<1) registered against corresponding images from the template IO.  This additional warp, the surfaces are much more precise and fewer vertices will be outside the scattered interpolant fov. It also imparts some nice smoothing effects since the warp from unfoldtemplate to unfold is a smooth one, so hopefully the curvature maps should look better than from the previous template-warped surfaces. 

A template surface (inner/outer/midthickness) is mapped with:
Warp_unfoldtemplate2unfold.nii  then Warp_unfold2native_extrapolateNearest.nii  

To do *before* merging: 
- Need to add `wb_command` as a dependency (ie add to autotop_deps), as this is used to create the Warp_unfold2unfoldtemplate warp; until then, could be done outside hippocampal_autotop
- Test on more cases @royhaast

### CODE REVIEW

**Comment by royhaast** [comment]
I've tested on one subject in my dataset and found a typo in line 15 `create_warps.m` (https://github.com/akhanf/Hippocampal_AutoTop/blob/master/tools/warps_gifti/create_warps.m#L15) needs minor fix:
`unfold_ref_nii = [path '/../../misc/unfold_ref_256x128x16.nii.gz'];`

And I get an error message when I run `extrapolate_warp_unfold2native`:
```
>> extrapolate_warp_unfold2native(in_folder, out_folder)
The logical indices contain a true value outside of the array bounds.

Error in extrapolate_warp_unfold2native (line 88)
    new_warp_abs_d(good_inds) = init_warp_abs_d(nan_mask==0);
```
The `mapUnfoldToFullGrid.sh` script works good up to the steps where it needs the `Warp_unfold2native_extrapolateNearest.nii` file.

**Comment by akhanf** [comment]
thanks @royhaast , I fixed the path typo (I have to stop making changes just before committing!)

re: the extrapolate_warp_unfold2native bug - I just ran on a fresh folder, but unable to reproduce the error -- can you point me to a folder with your data so I can try to reproduce it?

**Comment by royhaast** [comment]
Ok, maybe it's something I did wrong on my end. But the autotop output I tested on are here:
`/scratch/rhaast/HPC_perfusion/results/autotop-dev/work/autotop/sub-01/sub-01_hemi-R_space-CITI168corobl_desc-cropped_modality-segT2w_autotop`. As temp output folder I used: `/scratch/rhaast/HPC_perfusion/results/warps`

**Comment by akhanf** [comment]
@jordandekraker wasn't quite done with this, can you please revert? thanks

**Pull request merged**
